# This file is used to ignore specific rules for specific files or directories.
---
ignore:

# After quite some discussion on the team, we decided to make an exception to the
# "standard-isn't-supposed-to-be-configured" thing to allow for trailing comma, see
# https://github.com/standardrb/standard/issues/611 for a discussion
- '**/**':
  - Style/TrailingCommaInArguments
  - Style/TrailingCommaInArrayLiteral
  - Style/TrailingCommaInHashLiteral

# This disables standardrb for the rest of dd-trace-rb (other than profiling)
- .pryrc
- .simplecov
- Appraisals
- datadog.gemspec
- Gemfile
- Rakefile
- Steepfile
- appraisal/**/**
- benchmarks/**/**
- gemfiles/**/**
- integration/**/**
- lib-injection/**/**
- ext/libdatadog_extconf_helpers.rb
- ext/libdatadog_api/**/**
- lib/*
- lib/datadog/*
- lib/datadog/appsec/**/**
- lib/datadog/core/**/**
- lib/datadog/kit/**/**
- lib/datadog/opentelemetry/**/**
- lib/datadog/tracing/**/**
- spec/*
- spec/datadog/*
- spec/datadog/appsec/**/**
- spec/datadog/benchmark/**/**
- spec/datadog/core/**/**
- spec/datadog/kit/**/**
- spec/datadog/tracing/**/**
- spec/support/**/**
- tasks/**/**
- yard/**/**

# These profiling ignores are ALL going to be fixed in separate PRs
- lib/datadog/profiling/collectors/code_provenance.rb:
  - Style/StringLiterals
  - Layout/SpaceInsideHashLiteralBraces
- lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb:
  - Style/StringLiterals
  - Style/RedundantBegin
- lib/datadog/profiling/collectors/idle_sampling_helper.rb:
  - Style/RedundantBegin
  - Style/StringLiterals
- lib/datadog/profiling/collectors/info.rb:
  - Style/StringLiterals
- lib/datadog/profiling/component.rb:
  - Layout/SpaceInsideHashLiteralBraces
  - Style/StringLiterals
- lib/datadog/profiling/crashtracker.rb:
  - Style/StringLiterals
  - Style/RedundantBegin
- lib/datadog/profiling/exporter.rb:
  - Style/StringLiterals
- lib/datadog/profiling/ext.rb:
  - Style/StringLiterals
- lib/datadog/profiling/ext/dir_monkey_patches.rb:
  - Style/StringLiterals
- lib/datadog/profiling/ext/forking.rb:
  - Style/StringLiterals
- lib/datadog/profiling/flush.rb:
  - Style/StringLiterals
- lib/datadog/profiling/http_transport.rb:
  - Style/StringLiterals
- lib/datadog/profiling/load_native_extension.rb:
  - Style/StringLiterals
- lib/datadog/profiling/preload.rb:
  - Style/StringLiterals
- lib/datadog/profiling/profiler.rb:
  - Style/StringLiterals
- lib/datadog/profiling/scheduler.rb:
  - Style/StringLiterals
  - Style/RedundantBegin
- lib/datadog/profiling/tag_builder.rb:
  - Style/StringLiterals
- lib/datadog/profiling/tasks/exec.rb:
  - Style/StringLiterals
- lib/datadog/profiling/tasks/setup.rb:
  - Style/StringLiterals
  - Style/RedundantBegin
- lib/datadog/profiling.rb:
  - Style/StringLiterals
  - Style/RedundantBegin
- spec/datadog/profiling/collectors/code_provenance_spec.rb:
  - Style/StringLiterals
- spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb:
  - Style/StringLiterals
  - Layout/SpaceInsideHashLiteralBraces
  - Style/QuotedSymbols
  - Style/RedundantBegin
- spec/datadog/profiling/collectors/discrete_dynamic_sampler_spec.rb:
  - Style/StringLiterals
- spec/datadog/profiling/collectors/dynamic_sampling_rate_spec.rb:
  - Style/StringLiterals
- spec/datadog/profiling/collectors/idle_sampling_helper_spec.rb:
  - Style/StringLiterals
- spec/datadog/profiling/collectors/info_spec.rb:
  - Style/StringLiterals
  - Layout/SpaceInsideHashLiteralBraces
- spec/datadog/profiling/collectors/stack_spec.rb:
  - Style/StringLiterals
  - Layout/SpaceInsideHashLiteralBraces
- spec/datadog/profiling/collectors/thread_context_spec.rb:
  - Style/StringLiterals
  - Style/QuotedSymbols
  - Style/RedundantBegin
  - Layout/SpaceInsideHashLiteralBraces
- spec/datadog/profiling/component_spec.rb:
  - Style/StringLiterals
  - Layout/SpaceInsideHashLiteralBraces
- spec/datadog/profiling/crashtracker_spec.rb:
  - Style/StringLiterals
  - Layout/SpaceInsideHashLiteralBraces
  - Style/QuotedSymbols
- spec/datadog/profiling/exporter_spec.rb:
  - Style/StringLiterals
  - Layout/SpaceInsideHashLiteralBraces
- spec/datadog/profiling/ext/dir_monkey_patches_spec.rb:
  - Style/StringLiterals
  - Style/RedundantBegin
- spec/datadog/profiling/ext/forking_spec.rb:
  - Style/StringLiterals
- spec/datadog/profiling/flush_spec.rb:
  - Style/StringLiterals
  - Layout/SpaceInsideHashLiteralBraces
- spec/datadog/profiling/http_transport_spec.rb:
  - Style/StringLiterals
  - Layout/SpaceInsideHashLiteralBraces
  - Style/RedundantBegin
- spec/datadog/profiling/load_native_extension_spec.rb:
  - Style/StringLiterals
- spec/datadog/profiling/native_extension_helpers_spec.rb:
  - Style/StringLiterals
- spec/datadog/profiling/native_extension_spec.rb:
  - Style/StringLiterals
- spec/datadog/profiling/pprof/pprof_pb.rb:
  - Style/StringLiterals
- spec/datadog/profiling/preload_spec.rb:
  - Style/StringLiterals
- spec/datadog/profiling/profiler_spec.rb:
  - Style/StringLiterals
- spec/datadog/profiling/scheduler_spec.rb:
  - Style/StringLiterals
  - Layout/SpaceInsideHashLiteralBraces
- spec/datadog/profiling/spec_helper.rb:
  - Style/StringLiterals
  - Style/QuotedSymbols
- spec/datadog/profiling/stack_recorder_spec.rb:
  - Style/StringLiterals
  - Layout/SpaceInsideHashLiteralBraces
  - Style/QuotedSymbols
  - Style/RedundantBegin
- spec/datadog/profiling/tag_builder_spec.rb:
  - Style/StringLiterals
  - Layout/SpaceInsideHashLiteralBraces
- spec/datadog/profiling/tasks/exec_spec.rb:
  - Style/StringLiterals
- spec/datadog/profiling/tasks/help_spec.rb:
  - Style/StringLiterals
- spec/datadog/profiling/tasks/setup_spec.rb:
  - Style/StringLiterals
- spec/datadog/profiling/validate_benchmarks_spec.rb:
  - Style/StringLiterals
- spec/datadog/profiling_spec.rb:
  - Style/StringLiterals
  - Style/RedundantBegin
- ext/datadog_profiling_loader/extconf.rb:
  - Style/StringLiterals
- ext/datadog_profiling_native_extension/extconf.rb:
  - Style/StringLiterals
- ext/datadog_profiling_native_extension/native_extension_helpers.rb:
  - Style/StringLiterals
  - Layout/SpaceInsideHashLiteralBraces
  - Style/RedundantBegin
