name: Add milestone to merged pull requests
on:
  pull_request:
    types: [closed]

jobs:
  add_milestone:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.milestone == null
    steps:
      - name: Get project milestones
        id: milestones
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const milestones = await github.rest.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            })
            return milestones.data
      - name: Update Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const milestones = ${{steps.milestones.outputs.result}}
            let milestoneNumber = null

            if (github.event.pull_request.base.ref == 'master') {
              const milestone = milestones.find(m => m.title.startsWith('1'))
              if (milestone) milestoneNumber = milestone.number
            } else if (github.event.pull_request.base.ref == '2.0') {
              const milestone = milestones.find(m => m.title.startsWith('2'))
              if (milestone) milestoneNumber = milestone.number
            }

            if (milestoneNumber) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: github.event.pull_request.number,
                milestone: milestoneNumber
              })
            }
