name: "Library Injection"
on:
  # Build each branch for testing
  push:

jobs:
  build-and-publish-test-image:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        run: docker login -u publisher -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - name: Docker Build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/datadog/dd-trace-rb/dd-lib-ruby-init:${{ github.sha }}
          platforms: 'linux/amd64,linux/arm64/v8'
          build-args: DDTRACE_RUBY_SHA=${{ github.sha }}
          context: ./lib-injection
