name: System Tests

on:
  push:
    branches:
      - "**"
  workflow_dispatch: {}
  schedule:
    - cron:  '00 04 * * 2-6'

env:
  REGISTRY: ghcr.io

jobs:
  system-tests:
    strategy:
      fail-fast: false
      matrix:
        library:
          - ruby
        weblog-variant:
          - rack
          - sinatra14
          - sinatra20
          - sinatra21
          - rails32
          - rails40
          - rails41
          - rails42
          - rails50
          - rails51
          - rails52
          - rails60
          - rails61
          - rails70
    runs-on: ubuntu-latest
    name: System Tests (${{ matrix.weblog-variant }})
    steps:
      - name: Setup python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'DataDog/system-tests'

      - name: Checkout dd-trace-rb
        uses: actions/checkout@v3
        with:
          path: 'binaries/dd-trace-rb'

      - name: Log in to the Container registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Build
        run: ./build.sh --library ${{ matrix.library }} --weblog-variant ${{ matrix.weblog-variant }}

      - name: Run default scenario
        run: ./run.sh
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}
      - name: Run APPSEC_CUSTOM_RULES scenario
        run: ./run.sh APPSEC_CUSTOM_RULES
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}
      - name: Run APPSEC_CUSTOM_RULES scenario
        run: ./run.sh APPSEC_CUSTOM_RULES
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}
      - name: Run REMOTE_CONFIG_MOCKED_BACKEND_ASM_DD scenario
        run: ./run.sh REMOTE_CONFIG_MOCKED_BACKEND_ASM_DD
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}
      - name: Run REMOTE_CONFIG_MOCKED_BACKEND_ASM_FEATURES_NOCACHE scenario
        run: ./run.sh REMOTE_CONFIG_MOCKED_BACKEND_ASM_FEATURES_NOCACHE
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}
      - name: Run REMOTE_CONFIG_MOCKED_BACKEND_LIVE_DEBUGGING_NOCACHE scenario
        run: ./run.sh REMOTE_CONFIG_MOCKED_BACKEND_LIVE_DEBUGGING_NOCACHE
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}
      - name: Run REMOTE_CONFIG_MOCKED_BACKEND_ASM_DD_NOCACHE scenario
        run: ./run.sh REMOTE_CONFIG_MOCKED_BACKEND_ASM_DD_NOCACHE
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}
      - name: Run APPSEC_MISSING_RULES scenario
        run: ./run.sh APPSEC_MISSING_RULES
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}
      - name: Run APPSEC_CORRUPTED_RULES scenario
        if: steps.build.outcome == 'success' && github.event.action != 'opened' && !contains(github.event.pull_request.labels.*.name, 'run-default-scenario')
        run: ./run.sh APPSEC_CORRUPTED_RULES
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}
      - name: Run APPSEC_DISABLED scenario
        run: ./run.sh APPSEC_DISABLED
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}
      - name: Run APPSEC_LOW_WAF_TIMEOUT scenario
        run: ./run.sh APPSEC_LOW_WAF_TIMEOUT
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}
      - name: Run APPSEC_CUSTOM_OBFUSCATION scenario
        run: ./run.sh APPSEC_CUSTOM_OBFUSCATION
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}
      - name: Run APPSEC_RATE_LIMITER scenario
        run: ./run.sh APPSEC_RATE_LIMITER
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}
      - name: Run APPSEC_IP_BLOCKING scenario
        run: ./run.sh APPSEC_IP_BLOCKING
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}
      - name: Run APPSEC_REQUEST_BLOCKING scenario
        run: ./run.sh APPSEC_REQUEST_BLOCKING
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}
      - name: Run SAMPLING scenario
        run: ./run.sh SAMPLING
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}
      - name: Run PROFILING scenario
        run: ./run.sh PROFILING
        env:
          DD_API_KEY: ${{ secrets.DD_APPSEC_SYSTEM_TESTS_API_KEY }}

      - name: Archive logs
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: system-tests-${{ matrix.library }}-${{ matrix.weblog-variant }}-logs-${{ github.run_id }}-${{ github.sha }}
          path: logs*

      - name: Print fancy log report
        if: ${{ always() }}
        run: python utils/scripts/markdown_logs.py >> $GITHUB_STEP_SUMMARY
