name: Test cross-platform usage
on: [push]
jobs:
  test-head:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        ruby: [2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, '3.0', head]
    runs-on: ${{ matrix.os }}
    env:
      SKIP_SIMPLECOV: 1
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@77ca66ce2792fb05b8b204a203328e12593a64f3 # v1.72.1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake spec:main
