name: Update Gemfiles
on:
  push:
    paths:
      - Gemfile
      - Appraisals
      - ddtrace.gemspec

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Update Gemfiles
    runs-on: ubuntu-22.04
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: pr
      - if: steps.pr.outputs.pr_found == 'true'
        uses: actions/checkout@v4
      - if: steps.pr.outputs.pr_found == 'true'
        uses: ruby/setup-ruby@31a7f6d628878b80bc63375a93ae079ec50a1601 # v1.143.0
        with:
          ruby-version: '3.2'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - if: steps.pr.outputs.pr_found == 'true'
        name: Update gemfiles/*.gemfile
        run: bundle exec rake appraisal:generate
      - if: steps.pr.outputs.pr_found == 'true'
        name: Update gemfiles/*.gemfile.lock
        run: bundle exec rake appraisal:lock
      - if: steps.pr.outputs.pr_found == 'true'
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
        with:
          commit_message: Update gemfiles/*