name: Update Gemfiles
on:
  push:
    branches: [ master ]
    paths:
      - Gemfile
      - Appraisals
      - ddtrace.gemspec

  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
    paths:
      - Gemfile
      - Appraisals
      - ddtrace.gemspec
jobs:
  check:
    name: Update Gemfiles
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@31a7f6d628878b80bc63375a93ae079ec50a1601 # v1.143.0
        with:
          ruby-version: '3.2'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Update gemfiles/*.gemfile
        run: bundle exec rake appraisal:generate
      - name: Update gemfiles/*.gemfile.lock
        run: bundle exec rake appraisal:lock
      - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
        with:
          commit_message: Update gemfiles/*